# Main CroweTrade Platform - Frontend & API Gateway
app = "crowetrade-main"
primary_region = "iad"

[build]
  dockerfile = "docker/Dockerfile.frontend"

[env]
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://api.crowetrade.com"
  NEXT_PUBLIC_WS_URL = "wss://api.crowetrade.com/ws"

# HTTP Service Configuration
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

# Custom domains will be configured via flyctl commands
