# Main CroweTrade Platform - Frontend & API Gateway
app = "crowetrade-main"
primary_region = "iad"

[build]
  dockerfile = "docker/Dockerfile.frontend"

[env]
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://api.crowetrade.com"
  NEXT_PUBLIC_WS_URL = "wss://api.crowetrade.com/ws"

# Custom domain configuration
[[services]]
  internal_port = 3000
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 3

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  # Health check for Next.js app
  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "https"
    tls_skip_verify = false

# Domain mapping
[[http_service]]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

# Custom domains
[domains]
  primary = "crowetrade.com"
  
# SSL/TLS configuration
[certificates]
  auto_cert = true
