# Cryptocurrency Trading Configuration
# Configuration for CroweTrade AI Crypto Trading Infrastructure

crypto_trading:
  enabled: true
  
  # Exchange configurations
  exchanges:
    coinbase_pro:
      enabled: true
      # Set environment variables:
      # COINBASE_API_KEY, COINBASE_API_SECRET, COINBASE_PASSPHRASE
      sandbox: false
      rate_limits:
        orders_per_second: 10
        market_data_per_second: 100
      supported_pairs:
        - "BTC-USD"
        - "ETH-USD"
        - "ADA-USD"
        - "SOL-USD"
        - "MATIC-USD"
        - "USDC-USD"
    
    binance:
      enabled: true
      # For market data aggregation only
      websocket_url: "wss://stream.binance.com:9443/ws/"
      rest_url: "https://api.binance.com"
      supported_pairs:
        - "BTCUSDT"
        - "ETHUSDT"
        - "ADAUSDT"
        - "SOLUSDT"
        - "MATICUSDT"
    
    kraken:
      enabled: true
      # For market data aggregation only
      websocket_url: "wss://ws.kraken.com"
      rest_url: "https://api.kraken.com"
      supported_pairs:
        - "XBT/USD"
        - "ETH/USD"
        - "ADA/USD"
        - "SOL/USD"

  # Asset configurations
  assets:
    BTC:
      name: "Bitcoin"
      decimals: 8
      min_order_size: 0.0001
      tick_size: 0.01
      volatility_multiplier: 1.0
      correlation_group: "crypto_major"
      base_risk_weight: 1.0
      
    ETH:
      name: "Ethereum"
      decimals: 18
      min_order_size: 0.001
      tick_size: 0.01
      volatility_multiplier: 1.2
      correlation_group: "crypto_major"
      base_risk_weight: 0.8
      
    ADA:
      name: "Cardano"
      decimals: 6
      min_order_size: 1.0
      tick_size: 0.0001
      volatility_multiplier: 1.8
      correlation_group: "crypto_alt"
      base_risk_weight: 0.3
      
    SOL:
      name: "Solana"
      decimals: 9
      min_order_size: 0.01
      tick_size: 0.01
      volatility_multiplier: 2.0
      correlation_group: "crypto_alt"
      base_risk_weight: 0.4
      
    MATIC:
      name: "Polygon"
      decimals: 18
      min_order_size: 1.0
      tick_size: 0.0001
      volatility_multiplier: 2.2
      correlation_group: "crypto_alt"
      base_risk_weight: 0.2

  # Wallet configurations
  wallets:
    hot_wallets:
      max_balance_usd: 50000
      networks:
        bitcoin:
          enabled: true
          min_confirmations: 3
        ethereum:
          enabled: true
          min_confirmations: 12
          gas_price_strategy: "medium"
        polygon:
          enabled: true
          rpc_url: "https://polygon-rpc.com"
          min_confirmations: 10
        bsc:
          enabled: true
          rpc_url: "https://bsc-dataseed.binance.org"
          min_confirmations: 15
    
    cold_storage:
      threshold_usd: 10000
      require_multisig: true
      min_signers: 2
      total_signers: 3
      
    security:
      require_2fa: true
      transaction_monitoring: true
      max_daily_withdrawal_usd: 100000
      alert_large_transactions_usd: 25000

  # Risk management
  risk:
    portfolio_limits:
      max_crypto_allocation_pct: 30.0
      max_single_crypto_pct: 10.0
      max_alt_crypto_pct: 5.0
      max_leverage: 1.0
      
    volatility_targeting:
      enabled: true
      target_vol_annual: 0.20
      lookback_days: 30
      rebalance_frequency_hours: 6
      
    position_sizing:
      method: "kelly_tempered"
      kelly_fraction: 0.25
      min_position_usd: 100
      max_position_usd: 50000
      
    var_limits:
      portfolio_var_1d_pct: 5.0
      portfolio_var_7d_pct: 15.0
      individual_var_1d_pct: 3.0
      
    correlation_limits:
      max_crypto_correlation: 0.8
      max_sector_concentration: 0.6
      
    drawdown_controls:
      max_daily_drawdown_pct: 2.0
      max_weekly_drawdown_pct: 7.0
      portfolio_stop_loss_pct: 15.0
      
    regime_detection:
      enabled: true
      volatility_spike_threshold: 4.0
      volume_spike_threshold: 3.0
      correlation_breakdown_threshold: 0.3
      stand_down_duration_hours: 24

  # Execution settings
  execution:
    order_types:
      default: "limit"
      market_impact_threshold: 0.005
      
    limit_orders:
      default_offset_bps: 5
      max_offset_bps: 25
      order_refresh_seconds: 30
      
    market_orders:
      max_slippage_bps: 20
      size_threshold_usd: 10000
      
    smart_routing:
      enabled: true
      venue_scoring:
        liquidity_weight: 0.4
        fees_weight: 0.3
        fill_rate_weight: 0.2
        latency_weight: 0.1
      
    participation_limits:
      max_volume_participation_pct: 15.0
      max_order_book_pct: 5.0

  # Market data
  market_data:
    aggregation:
      enabled: true
      consensus_method: "volume_weighted"
      outlier_threshold: 3.0
      
    features:
      technical_indicators:
        - "rsi"
        - "macd"
        - "bollinger_bands"
        - "volume_profile"
        
      microstructure:
        - "bid_ask_spread"
        - "order_book_imbalance"
        - "trade_intensity"
        
      cross_asset:
        - "btc_dominance"
        - "fear_greed_index"
        - "funding_rates"
        
    update_frequency_ms: 1000
    history_days: 365

  # Strategy configurations
  strategies:
    momentum:
      enabled: true
      lookback_periods: [5, 20, 60]
      signal_threshold: 0.02
      max_allocation_pct: 15
      
    mean_reversion:
      enabled: true
      zscore_entry: 2.0
      zscore_exit: 0.5
      max_allocation_pct: 10
      
    arbitrage:
      enabled: true
      min_spread_bps: 10
      max_execution_time_seconds: 30
      max_allocation_pct: 5
      
    trend_following:
      enabled: true
      ema_periods: [12, 26, 50]
      atr_multiplier: 2.0
      max_allocation_pct: 20

  # Monitoring and alerts
  monitoring:
    performance_tracking:
      update_frequency_seconds: 300
      benchmark: "BTC-USD"
      
    alerts:
      email_enabled: true
      slack_enabled: false
      
      thresholds:
        portfolio_loss_pct: 3.0
        position_loss_pct: 5.0
        system_error_count: 5
        api_error_rate_pct: 10.0
        
    metrics:
      sharpe_ratio_lookback_days: 30
      max_drawdown_lookback_days: 90
      win_rate_lookback_trades: 100

  # Compliance and governance
  compliance:
    trade_reporting:
      enabled: true
      format: "json"
      retention_days: 2555  # 7 years
      
    audit_trail:
      enabled: true
      log_level: "INFO"
      include_pii: false
      
    restricted_assets:
      # List any restricted crypto assets
      blacklist: []
      
    position_limits:
      per_asset_usd: 100000
      per_strategy_usd: 200000
      total_crypto_usd: 500000

  # Development and testing
  development:
    paper_trading:
      enabled: false
      initial_balance_usd: 1000000
      
    backtesting:
      start_date: "2023-01-01"
      end_date: "2024-12-31"
      commission_bps: 5
      slippage_bps: 2
      
    simulation:
      monte_carlo_runs: 1000
      confidence_level: 0.95

# Integration with main CroweTrade configuration
venues:
  coinbase_pro:
    adapter_class: "CoinbaseProVenueAdapter"
    config_section: "crypto_trading.exchanges.coinbase_pro"
    
features:
  crypto_features:
    enabled: true
    update_frequency: "1s"
    
risk:
  crypto_overlay:
    enabled: true
    config_section: "crypto_trading.risk"
