environment: development
debug: true

market_data:
  providers:
    - polygon
    - alpaca
  tick_buffer_size: 10000
  snapshot_interval: 60
  max_reconnect_attempts: 5
  reconnect_delay: 1.0

brokers:
  - name: alpaca
    api_key: ${ALPACA_API_KEY}
    api_secret: ${ALPACA_API_SECRET}
    base_url: https://paper-api.alpaca.markets
    paper_trading: true
    rate_limit: 200
    
  - name: interactive_brokers
    api_key: ${IB_API_KEY}
    account_id: ${IB_ACCOUNT_ID}
    base_url: localhost:7497
    paper_trading: true
    rate_limit: 50

risk:
  max_position_size: 0.1
  max_leverage: 1.0
  max_drawdown: 0.05
  intraday_loss_limit: 0.02
  var_limit: 0.015
  position_limits:
    AAPL: 0.05
    GOOGL: 0.05
    MSFT: 0.05
  restricted_symbols:
    - RESTRICTED1
    - RESTRICTED2

execution:
  default_algo: LIMIT
  max_order_size: 10000
  participation_rate: 0.1
  slippage_model: linear
  urgency: normal
  smart_routing: true

features:
  lookback_periods:
    - 5
    - 10
    - 20
    - 50
    - 100
  update_frequency: 60
  max_feature_lag: 300
  cache_size: 10000

database:
  timescale_url: ${DATABASE_URL}
  redis_url: ${REDIS_URL}
  max_connections: 20
  connection_timeout: 30

monitoring:
  prometheus_port: 9090
  grafana_url: http://localhost:3000
  alert_webhook: ${ALERT_WEBHOOK_URL}
  log_level: INFO
  metrics_interval: 10