# Railway.app deployment configuration for crowetrade.com
# Alternative cloud deployment option

[build]
  builder = "DOCKERFILE"
  dockerfilePath = "docker/Dockerfile"

[deploy]
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[environments.production]
  [environments.production.variables]
  ENVIRONMENT = "production"
  TRADING_MODE = "PAPER"
  LOG_LEVEL = "INFO"
  SERVICE_PORT = "8080"
  PYTHONPATH = "/app/src"