name: Deploy CroweTrade to Fly.io

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  COINBASE_API_KEY: ${{ secrets.COINBASE_API_KEY }}
  COINBASE_API_SECRET: ${{ secrets.COINBASE_API_SECRET }}
  COINBASE_PASSPHRASE: ${{ secrets.COINBASE_PASSPHRASE }}

jobs:
  deploy-web:
    name: Deploy Web Frontend
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Fly CLI
      uses: superfly/flyctl-actions/setup-flyctl@master
    
    - name: Deploy Web Frontend
      run: |
        flyctl deploy --config fly.frontend.toml --app crowetrade-web --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-execution:
    name: Deploy Execution Engine  
    runs-on: ubuntu-latest
    needs: deploy-web
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Fly CLI
      uses: superfly/flyctl-actions/setup-flyctl@master
      
    - name: Deploy Execution Engine
      run: |
        flyctl deploy --config fly.execution.toml --app crowetrade-execution
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-portfolio:
    name: Deploy Portfolio Service
    runs-on: ubuntu-latest
    needs: deploy-execution
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Fly CLI
      uses: superfly/flyctl-actions/setup-flyctl@master
      
    - name: Deploy Portfolio Service
      run: |
        flyctl deploy --config fly.portfolio.toml --app crowetrade-portfolio
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  configure-domains:
    name: Configure Custom Domains
    runs-on: ubuntu-latest
    needs: [deploy-web, deploy-execution, deploy-portfolio]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Fly CLI
      uses: superfly/flyctl-actions/setup-flyctl@master
      
    - name: Configure Domains
      run: |
        # Add custom domains
        flyctl certs create crowetrade.com --app crowetrade-web || true
        flyctl certs create www.crowetrade.com --app crowetrade-web || true
        flyctl certs create api.crowetrade.com --app crowetrade-execution || true
        flyctl certs create portfolio.crowetrade.com --app crowetrade-portfolio || true
        
        # Show certificate status
        flyctl certs list --app crowetrade-web
        
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
